import React from 'react';

export const PrivacyPolicy: React.FC = () => (
  <div className="max-w-4xl mx-auto py-24 px-4">
    <h1 className="text-4xl font-bold text-slate-900 mb-8">Privacy Policy</h1>
    <div className="prose prose-slate max-w-none text-slate-600 space-y-6">
      <p>Last updated: {new Date().toLocaleDateString()}</p>

      <h3 className="text-xl font-bold text-slate-900">1. Overview</h3>
      <p>Bookmarks as Thumbnails ("the Extension") is designed with a "Local First" architecture. We believe your browsing data is yours alone. We do not collect, store, or transmit your personal data, bookmark URLs, or generated thumbnails to any external servers.</p>

      <h3 className="text-xl font-bold text-slate-900">2. Data Storage</h3>
      <p>All data generated by the extension is stored locally on your device using:</p>
      <ul className="list-disc pl-5 space-y-2">
        <li><strong>IndexedDB:</strong> Used to store thumbnail images and bookmark metadata for quick access.</li>
        <li><strong>Chrome Local Storage:</strong> Used to store user preferences (e.g., theme settings, view modes).</li>
      </ul>

      <h3 className="text-xl font-bold text-slate-900">3. Third-Party Services</h3>
      <p>The Extension operates independently and does not utilize third-party analytics services (like Google Analytics) within the extension background or popup pages.</p>

      <h3 className="text-xl font-bold text-slate-900">4. Permissions</h3>
      <p>We request the minimum permissions necessary to function:</p>
      <ul className="list-disc pl-5 space-y-2">
        <li><strong>Bookmarks:</strong> To read and organize your bookmarks.</li>
        <li><strong>ActiveTab/Tabs:</strong> To capture screenshots of pages for thumbnail generation.</li>
      </ul>
    </div>
  </div>
);

export const TermsAndConditions: React.FC = () => (
  <div className="max-w-4xl mx-auto py-24 px-4">
    <h1 className="text-4xl font-bold text-slate-900 mb-8">Terms & Conditions</h1>
    <div className="prose prose-slate max-w-none text-slate-600 space-y-6">
      <p>By installing and using the Bookmarks as Thumbnails extension, you agree to the following terms:</p>

      <h3 className="text-xl font-bold text-slate-900">1. Usage License</h3>
      <p>This software is dual-licensed:</p>
      <ul className="list-disc pl-5 space-y-2">
        <li><strong>Free/Open Source:</strong> You may use this software under the terms of the GNU Affero General Public License v3 (AGPLv3) for non-commercial or open-source purposes.</li>
        <li><strong>Commercial:</strong> For proprietary or commercial use without the AGPLv3 restrictions, a commercial license must be purchased.</li>
      </ul>

      <h3 className="text-xl font-bold text-slate-900">2. Disclaimer of Warranty</h3>
      <p>The Extension is provided "AS IS" without warranty of any kind. We make no guarantees that the software will be error-free, uninterrupted, or compatible with all systems. We are not responsible for any data loss associated with the use of this software (though we provide backup tools to mitigate this risk).</p>

      <h3 className="text-xl font-bold text-slate-900">3. Changes to Terms</h3>
      <p>We reserve the right to modify these terms at any time. Significant changes will be communicated via our changelog.</p>
    </div>
  </div>
);

export const GetInTouch: React.FC = () => (
  <div className="max-w-2xl mx-auto py-24 px-4 text-center">
    <h1 className="text-4xl font-bold text-slate-900 mb-6">Get in Touch</h1>
    <p className="text-lg text-slate-600 mb-10">
      Have a feature request, found a bug, or just want to say hi? We'd love to hear from you.
    </p>

    <div className="bg-slate-50 p-8 rounded-2xl border border-slate-200">
      <p className="font-medium text-slate-900 mb-2">Support Email</p>
      <a href="mailto:support@palworks.ai" className="text-2xl font-bold text-brand-600 hover:text-brand-700 transition-colors">
        support@palworks.ai
      </a>

      <div className="my-8 h-px bg-slate-200 w-full" />

      <p className="font-medium text-slate-900 mb-2">Social</p>
      <div className="flex justify-center gap-4">
        <a href="#" className="text-slate-500 hover:text-brand-600">Twitter / X</a>
        <span className="text-slate-300">•</span>
        <a href="#" className="text-slate-500 hover:text-brand-600">GitHub Issues</a>
      </div>
    </div>
  </div>
);